### ISSUE TITLE
promisifyRoutine should create unique ids for dispatched actions

### ISSUE THREAD

**Issue by ancestorak** [afitiskin/redux-saga-routines#28] opened 2018-01-10 00:37 UTC
Let me start by saying I really appreciate your work on this library. It helped us reduce boilerplate, enforce clear lifecycle for async actions, and made it easy to integrate with redux-form and other libraries that deal with promises.

The problem with the `promisifyRoutine`/`routinePromiseWatcherSaga` combo is they fail to handle the case when a routine is dispatched again before the previous one is fulfilled. As soon as the first SUCCESS comes in, all the pending promises are resolved.

The solution would be to give each `ROUTINE_PROMISE_ACTION` a unique id. Would you accept a PR to this effect?

**Comment by afitiskin** [comment] 2018-01-10 14:30
@ancestorak let's start with some example code that shows the problem. I think PR with failing test case is a good starting point. I will check it and we will discuss the variants to solve the problem. Thank you!

PS. I think the problem is related to #26

**Comment by ckeeney** [comment] 2018-01-10 18:39
I agree, this looks identical to the behavior I discussed in #26.

**Comment by stefanfrede** [comment] 2018-08-26 14:42
Hi!

I guess I ran into exactly this problem. I fire up a couple of routines and each takes some time to fulfil and because of that everything is getting resolved with the first fulfilment.

Is there a solution for that in the pipeline or some existing workaround?

Thanks!

**Comment by stefanfrede** [comment] 2018-08-29 16:13
I found a workaround for my case but just realised that if the first routine is failing that all successive routines are failing too.

Same goes for a failing routine after a successful one. It will get resolved with the success method.

**Comment by stefanfrede** [comment] 2018-08-29 16:15
@ancestorak You wrote that you have a solution. Is it difficult to implement? I have to admit that I have no clue why it is failing, but maybe with a push in the right direction, I can be of help.

**Comment by stefanfrede** [comment] 2018-08-29 20:47
Will try to setup something to show the problem.

**Comment by stefanfrede** [comment] 2018-09-10 18:18
Sorry, it took a bit longer than expected.

I hope I can explain it with the following piece of code:
```js
async getUser(request) {
  return new Promise(resolve =>
    usersRoutinePromiseCreator(
      { type: REQUEST_USER, payload: request },
      store.dispatch,
    ).then(
      successPayload => resolve(successPayload),
      failurePayload => resolve(failurePayload),
    ),
  )
}
```
This method is working as expected except for when I do something like this:
```js
getUser('A').then(console.log);
getUser('B').then(console.log);
getUser('C').then(console.log);
```
The first `getUser` call returns the correct user, but every following call thereafter is then resolved with the payload of the first call.

In the Redux store, I have all three users correctly, so it has to do with how the `usersRoutinePromiseCreator` is getting resolved.

What would work is something like this:
```js
getUser('A').then(console.log);
setTimeout(() => {getUser('B').then(console.log)}, 1000);
setTimeout(() => {getUser('C').then(console.log)}, 1000);
```
This would return me all three users, but sadly I can't use this  in my case.

I hope this explains the problem.

If not, please let me know!

**Comment by afitiskin** [comment] 2018-09-10 18:35
Ok, thank you! I'm on vacations right now, will take a closer look soon

**Comment by afitiskin** [comment] 2018-09-20 14:00
I spent some time on the task and found that routines (in it's current implementation) could not help you... The main problem is that we have no relations between `trigger` action and all following actions (`request`, `success` / `failure` and `fulfill`) so we can't distinct which `success`/`failure` action should resolve/reject our promise.

As a first attempt, I tried to update `promisifyRoutine` and `handleRoutinePromiseAction`. I added internal `id` to action' `meta` data and instead of just `take(routine.SUCCESS)`/`take(routine.FAILURE)` I started to use more complex function with check for `id` equality. But this internal `id` should be passed to `routine.success()`/`routine.failure()`, which are the part of your application code (not `redux-saga-routines` library), so I need somehow to pass this `id` to your code, but there is no way to do that :) (since routine is just an action creator, so the result of `routine.trigger()` is an action object, and `promisifyRoutine` is just a wrapper, which returns `Promise`)

As a second attempt, I tried to create new structure `smartRoutine`. The main idea of `smartRoutine` is to have shared internal `id` between `trigger` and all following lifecycle action creators. But again I faced the same problem: you have to know internal `id` and pass this `id` explicitly in your code to tell the library which exactly routine-based promise you are going to resolve or reject...

And now I keep in mind other way to solve the problem: create something like routine factory:

```javascript
const getUserRoutineFactory = createRoutineFactory('GET_USER');

const getUserARoutine = getUserRoutineFactory('A');
const getUserAPromise = promisifyRoutine(getUserARoutine);

const getUserB = getUserRoutineFactory('B');
const getUserBPromise = promisifyRoutine(getUserBRoutine);
```

But, I see no reason to implement it inside the library since it may be easily implemented in your code to cover your own use case.

PS. It is very simple to refactor your code to solve the problem, I'm not sure why you are using promises in your code explicitly, I see no reason to do that.

**Comment by stefanfrede** [comment] 2018-09-20 15:08
> PS. It is very simple to refactor your code to solve the problem, I'm not sure why you are using promises in your code explicitly, I see no reason to do that.

I wouldn't say no to a hint how to refactor this ;) To use promises was the first thing which came to my mind on how to solve my use case, but I don't need to use them if I don't have to.

Thank you very much for looking into this!

**Comment by afitiskin** [comment] 2018-09-21 14:13
Is your `getUser` function a part of some component? Why it should return a promise? Do you really need N promises for N requests instead or you may be okay with just one for all of them?

**Comment by stefanfrede** [comment] 2018-09-22 16:06
Yes, the function is part of some kind of API where you can request data over a socket connection. Because multiple asynchronous requests can happen I thought it is best to return those requests via a promise. After thinking a bit about it I guess I need N promises for N requests.

**Comment by afitiskin** [comment] 2018-09-24 09:43
Is it a part of API of the component? How are you using it? I think there is a simple solution for your case but I can't suggest something without an idea what you are going to achieve....

**Comment by stefanfrede** [comment] 2018-09-24 10:30
The workflow is that if you instantiate my class, you get a socket connection and then you are able to request data from the backend via REST parameters over this socket connection.

Every time you request something, the data is stored in the Redux store, but I also need to return the result.

This is why I thought the promise solution would work nicely. You fire up your request action and just wait for the success action to return in a promise.

I stumbled over [redux-listen](https://github.com/heiskr/redux-listen) with which you can listen to dispatched actions, and with that, I managed to resolve my use case, but if you have a simpler solution in mind, I would be very happy to learn about it. I generally don't like the idea to throw library after library at a problem to solve it if you are able to get it done more simply.

**Comment by afitiskin** [comment] 2018-09-24 10:58
`redux-saga-routines` and especially promisifying routines are designed for usage inside the components. You described the case that is not related to the components world (view) but to the side-effects (sagas). So it is better to achieve your goal in the saga. You may use promises, you may use routines, but you do not need to depend on them 100%. 

IMO, API part that keeps socket connection, makes requests and gets responses from server may be implemented without routines and sagas at all. It is like an `axios` instance, that works using sockets instead of XHR or fetch. It is just a network layer not related to your app logic, so keep it as simple as possible. You may reuse it in your other apps (using other stack of technologies). 

Let's assume that you created your API library (network layer) and have something like `api.request('/my/app/endpoint', { some: 'data' }) => Promise`. Now your are able to use it inside your sagas and store requested data in the redux-store, just like you are using `axios` or any other library.

And I see no reason to use `redux-listen` since you are using `redux-saga`, because there is a `take` effect in 'redux-saga' that does exactly the same that `redux-listen` does.

**Comment by afitiskin** [comment] 2018-10-04 15:27
No changes will be implemented in library, so issue may be closed.

**Closed by afitiskin** 2018-10-04 15:27 UTC
